# Generated by Django 5.1.4 on 2025-01-02 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0002_alter_userprofile_options_userprofile_cgpa_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='experience',
            name='user_profile',
        ),
        migrations.RemoveField(
            model_name='project',
            name='user_profile',
        ),
        migrations.AlterModelOptions(
            name='userprofile',
            options={},
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='cgpa',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='graduation_year',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='last_updated',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='score_breakdown',
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='department',
            field=models.CharField(choices=[('CSE', 'Computer Science'), ('ECE', 'Electronics'), ('ME', 'Mechanical'), ('IT', 'Information Technology'), ('Other', 'Other')], max_length=50),
        ),
        migrations.DeleteModel(
            name='Certification',
        ),
        migrations.DeleteModel(
            name='Experience',
        ),
        migrations.DeleteModel(
            name='Project',
        ),
    ]
